-- ILEastic demo database, using stored procedures to decouple SQL

-- Setup database:
--drop schema microdemo;
create schema microdemo;
set schema microdemo;
--drop table microdemo.ilproducts;


-- A list of products
create or replace table microdemo.ilproducts (
    id int generated always as identity primary key,
    prodKey varchar(32),
    desciption varchar(256),
    manuid character(30),
    price decimal(11, 2),
    stockcnt int,
    stockdate date
); 

label on table microdemo.ilproducts is 'Demo products';

label on microdemo.ilproducts (
    id          is  'Product Id',
    prodKey     is  'Prduct public Key',
    desciption  is  'Description',
    manuid      is  'Manufacturer',
    price       is  'Price',
    stockcnt    is  'Items in stock',
    stockdate   is  'Available from date'
); 


truncate microdemo.ilproducts;
insert into microdemo.ilproducts (
    prodKey,
    desciption,
    manuid,
    price,
    stockcnt,
    stockdate
 )
 values 
('µDIGITAL 600 ax','Camera Plus','CASIO',1585.0,int(rand()* 100),now() - int(rand() * 100) days),
('µDIGITAL 600 ex','Super flex XL plus','OLYMPUS',3005.8,int(rand()* 100),now() - int(rand() * 100) days),
('µ-mini DIGITAL','Digitalkamera - 50 Mpix - optisk zoom: 2 x - understøttet hukommelse: xD-Picture Card','OLYMPUS',2667.12,int(rand()* 100),now() - int(rand() * 100) days),
('µ-mini DIGITAL S','Digitalkamera - 50 Mpix - optisk zoom: 2 x - understøttet hukommelse: xD-Picture Card - blank beige','OLYMPUS',3094.06,int(rand()* 100),now() - int(rand() * 100) days),
('µmini DIGITAL S','Digitalkamera - 50 Mpix - optisk zoom: 2 x - understøtet hukommelse: xD-Picture Card - emaljesort','OLYMPUS',2579.47,int(rand()* 100),now() - int(rand() * 100) days),
('µmini DIGITAL S','Digitalkamera - 50 Mpix - optisk zoom: 2 x - understøtet hukommelse: xD-Picture Card - lagunebl√•ure Card - emaljesort','OLYMPUS',2281.85,int(rand()* 100),now() - int(rand() * 100) days),
('µmini DIGITAL S','Digitalkamera - 50 Mpix - optisk zoom: 2 x - understøtet hukommelse: xD-Picture Card - guld','OLYMPUS',1378.86,int(rand()* 100),now() - int(rand() * 100) days),
('µ[MJU:] DIGITAL 800','Digitalkamera - 80 Mpix - optisk zoom: 3 x - understøtet hukommelse: xD-Picture Card - møkebl√•Card - møkebl√•','OLYMPUS',3095.73,int(rand()* 100),now() - int(rand() * 100) days),
('µ[MJU:] DIGITAL 800','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøtet hukommelse: xD-Picture Card','OLYMPUS',3069.59,int(rand()* 100),now() - int(rand() * 100) days),
('µ[MJU:] mini DIGITAL','Digitalkamera - 40 Mpix - optisk zoom: 2 x - understøttet hukommelse: xD-Picture Card - kosmisk sort','OLYMPUS',2461.64,int(rand()* 100),now() - int(rand() * 100) days),
('µ[MJU:] mini DIGITAL','Digitalkamera - 40 Mpix - optisk zoom: 2 x - understøttet hukommelse: xD-Picture Card - ren hvid','SAMSUNG',1234.0,int(rand()* 100),now() - int(rand() * 100) days),
('CAMEDIA AZ-2 Zoom','Digitalkamera - 40 Mpix - optisk zoom: 28 x - understøttet hukommelse: xD-Picture Card','SAMSUNG',1234.0,int(rand()* 100),now() - int(rand() * 100) days),
('Flexi-mate','Cool Flexi','SONY',2730.93,int(rand()* 100),now() - int(rand() * 100) days),
('CAMEDIA C-370 Zoom','Digitalkamera - 32 Mpix - optisk zoom: 3 x - understøttet hukommelse: xD-Picture Card','OLYMPUS',2363.7,int(rand()* 100),now() - int(rand() * 100) days),
('CAMEDIA C-480 ZOOM','Digitalkamera - 40 Mpix - optisk zoom: 3 x - understøttet hukommelse: xD-Picture Card','OLYMPUS',2064.35,int(rand()* 100),now() - int(rand() * 100) days),
('CAMEDIA C-500 Zoom','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: xD-Picture Card','OLYMPUS',1421.1,int(rand()* 100),now() - int(rand() * 100) days),
('CAMEDIA C-55ZOOM','Digitalkamera - 51 Mpix - optisk zoom: 5 x - understøttet hukommelse: xD-Picture Card','OLYMPUS',2871.63,int(rand()* 100),now() - int(rand() * 100) days),
('CAMEDIA C-70ZOOM','Digitalkamera - 71 Mpix - optisk zoom: 5 x - understøttet hukommelse: xD-Picture Card - titan','OLYMPUS',3053.44,int(rand()* 100),now() - int(rand() * 100) days),
('CAMEDIA C-770 Ultra Zo','Digitalkamera - 40 Mpix / 77 Mpix (interpoleret) - optisk zoom: 10 x - understøttet hukommelse: xD-Picture Card','OLYMPUS',1894.2,int(rand()* 100),now() - int(rand() * 100) days),
('CAMEDIA FE-5500','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: xD-Picture Card','OLYMPUS',2497.57,int(rand()* 100),now() - int(rand() * 100) days),
('CE-5330','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: SD - Guld','ACER',1300.41,int(rand()* 100),now() - int(rand() * 100) days),
('Grande SXL','Megapix','SONY',2437.11,int(rand()* 100),now() - int(rand() * 100) days),
('√òI-6330','Digitalkamera - 60 Mpix - optisk zoom: 3 x - understøttet hukommelse: SD - sølv','ACER',1557.55,int(rand()* 100),now() - int(rand() * 100) days),
('Coolpix P1','Digitalkamera - 80 Mpix - optisk zoom: 35 x - understøttet hukommelse: SD - sort','NIKON',2342.55,int(rand()* 100),now() - int(rand() * 100) days),
('Coolpix P2','Digitalkamera - 51 Mpix - optisk zoom: 35 x - understøttet hukommelse: SD - sølv','NIKON',2916.21,int(rand()* 100),now() - int(rand() * 100) days),
('Coolpix S1','Digitalkamera - 51 Mpix - optisk zoom: 3 x - understøttet hukommelse: SD - elfenbenshvid','NIKON',3009.65,int(rand()* 100),now() - int(rand() * 100) days),
('Coolpix S1','Digitalkamera - 51 Mpix - optisk zoom: 3 x - understøttet hukommelse: SD - ibenholtsort','NIKON',3009.65,int(rand()* 100),now() - int(rand() * 100) days),
('Coolpix S1','Digitalkamera - 51 Mpix - optisk zoom: 3 x - understøttet hukommelse: SD - pure silver','NIKON',3034.94,int(rand()* 100),now() - int(rand() * 100) days),
('Coolpix S3','Digitalkamera - 60 Mpix - optisk zoom: 3 x - understøttet hukommelse: SD - platinsølv','NIKON',2951.1,int(rand()* 100),now() - int(rand() * 100) days),
('Coolpix S4','Digitalkamera - 60 Mpix - optisk zoom: 10 x - understøttet hukommelse: SD','NIKON',2342.55,int(rand()* 100),now() - int(rand() * 100) days),
('Coolpix 2500','Digitalkamera - 20 Mpix - optisk zoom: 3 x - understøttet hukommelse: CF - bl√•, sølv','NIKON',1878.29,int(rand()* 100),now() - int(rand() * 100) days),
('Coolpix 4600','Digitalkamera - 40 Mpix - optisk zoom: 3 x - understøttet hukommelse: SD - sølv','NIKON',2355.76,int(rand()* 100),now() - int(rand() * 100) days),
('Coolpix 5600','Digitalkamera - 51 Mpix - optisk zoom: 3 x - understøttet hukommelse: SD - sølv','NIKON',2107.67,int(rand()* 100),now() - int(rand() * 100) days),
('Coolpix 5900','Digitalkamera - 51 Mpix - optisk zoom: 3 x - understøttet hukommelse: SD','NIKON',1747.94,int(rand()* 100),now() - int(rand() * 100) days),
('Coolpix 7600','Digitalkamera - 71 Mpix - optisk zoom: 3 x - understøttet hukommelse: SD - sort','NIKON',1979.98,int(rand()* 100),now() - int(rand() * 100) days),
('Coolpix 7600','Digitalkamera - 71 Mpix - optisk zoom: 3 x - understøttet hukommelse: SD - sølv','NIKON',2571.48,int(rand()* 100),now() - int(rand() * 100) days),
('Coolpix 7900','Digitalkamera - 71 Mpix - optisk zoom: 3 x - understøttet hukommelse: SD - sort','NIKON',2178.09,int(rand()* 100),now() - int(rand() * 100) days),
('Coolpix 7900','Digitalkamera - 71 Mpix - optisk zoom: 3 x - understøttet hukommelse: SD - sølv','NIKON',2202.68,int(rand()* 100),now() - int(rand() * 100) days),
('Coolpix 8400','Digitalkamera - 80 Mpix - optisk zoom: 35 x - understøttet hukommelse: CF, Microdrive','NIKON',2566.56,int(rand()* 100),now() - int(rand() * 100) days),
('CR-8530CR','Digitalkamera - 80 Mpix - optisk zoom: 3 x - understøttet hukommelse: SD - sort','ACER',2922.35,int(rand()* 100),now() - int(rand() * 100) days),
('CR-8530','Digitalkamera - 80 Mpix - optisk zoom: 3 x - understøttet hukommelse: SD - sort','ACER',2922.35,int(rand()* 100),now() - int(rand() * 100) days),
('CS-5530','Digitalkamera - 52 Mpix - optisk zoom: 3 x - understøttet hukommelse: SD - sølv','ACER',1386.14,int(rand()* 100),now() - int(rand() * 100) days),
('CS-5530','Digitalkamera - 52 Mpix - optisk zoom: 3 x - understøttet hukommelse: SD - sølv','ACER',1403.89,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-F88/S','Digitalkamera - 51 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick, Memory Stick Duo, Memory Stick PRO, Memory Stick PRO Duo - sølv','SONY',2448.43,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-H1','Digitalkamera - 51 Mpix - optisk zoom: 12 x - understøttet hukommelse: Memory Stick, Memory Stick PRO','SONY',2256.37,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-H1','Digitalkamera - SLR-type - 51 Mpix - optisk zoom: 12 x - understøttet hukommelse: Memory Stick, Memory Stick PRO','SONY',2392.6,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-L1/B','Digitalkamera - 41 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick Duo, Memory Stick PRO Duo - sort','SONY',1558.49,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-L1/B','Digitalkamera - 41 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick Duo, Memory Stick PRO Duo - sort','SONY',2571.98,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-L1/L','Digitalkamera - 41 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick Duo, Memory Stick PRO Duo - bl√•','SONY',3033.42,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-L1/LJ','Digitalkamera - 41 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick Duo, Memory Stick PRO Duo - bl√•','SONY',2116.52,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-L1/S','Digitalkamera - 41 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick Duo, Memory Stick PRO Duo - sølv','SONY',2794.86,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-L1/S','Digitalkamera - 41 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick Duo, Memory Stick PRO Duo - sølv','SONY',2965.83,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-P100R','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick, Memory Stick Duo, Memory Stick PRO, Memory Stick PRO Duo - rød','SONY',2383.28,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-P120','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick, Memory Stick Duo, Memory Stick PRO, Memory Stick PRO Duo - sort','SONY',2366.89,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-P200/B','Digitalkamera - 72 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick, Memory Stick PRO - sort','SONY',2743.5,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-P200/S','Digitalkamera - 72 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick, Memory Stick PRO - sølv','SONY',1456.28,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-S40','Digitalkamera - 41 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick, Memory Stick PRO','SONY',1789.08,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-S40','Digitalkamera - 41 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick, Memory Stick PRO','SONY',2347.07,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-S60','Digitalkamera - 41 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick, Memory Stick PRO','SONY',1772.51,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-S60','Digitalkamera - 41 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick, Memory Stick PRO','SONY',1626.83,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-S80','Digitalkamera - 41 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick, Memory Stick PRO','SONY',2973.93,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-S80','Digitalkamera - 41 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick, Memory Stick PRO','SONY',1721.06,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-S90','Digitalkamera - 41 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick, Memory Stick PRO','SONY',2630.96,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-S90S','Digitalkamera - 41 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick, Memory Stick PRO - sølv','SONY',1679.25,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-S90S','Digitalkamera - 41 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick, Memory Stick PRO - sølv','SONY',2682.26,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-T1','Digitalkamera - 51 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick Duo, Memory Stick PRO Duo','SONY',1835.29,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-T3/B','Digitalkamera - 51 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick Duo, Memory Stick PRO Duo - sort','SONY',1448.36,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-T3/S','Digitalkamera - 51 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick Duo, Memory Stick PRO Duo - sølv','SONY',1912.97,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-T33','Digitalkamera - 51 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick Duo','SONY',1320.31,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-T33/N','Digitalkamera - 51 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick Duo - guld','SONY',1294.48,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-T5','Digitalkamera - 51 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick Duo, Memory Stick PRO Duo - sort','SONY',2357.38,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-T5','Digitalkamera - 51 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick Duo, Memory Stick PRO Duo - sølv','SONY',2357.38,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-T7/B','Digitalkamera - 51 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick Duo, Memory Stick PRO Duo - sort','SONY',2839.04,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-T7/B','Digitalkamera - 51 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick Duo, Memory Stick PRO Duo - sort','SONY',2461.46,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-T7/S','Digitalkamera - 51 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick Duo, Memory Stick PRO Duo - sølv','SONY',1328.57,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-T7/S','Digitalkamera - 51 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick Duo, Memory Stick PRO Duo - sølv','SONY',1430.67,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-V3','Digitalkamera - 72 Mpix - optisk zoom: 4 x - understøttet hukommelse: CF, Memory Stick, Memory Stick PRO','SONY',3217.06,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-W15','Digitalkamera - 51 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick, Memory Stick PRO - sort','SONY',2133.45,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-W17','Digitalkamera - 71 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD - sølv','SAMSUNG',2500.89,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-W5','Digitalkamera - 51 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick, Memory Stick PRO - sølv','SONY',1987.75,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-W5','Digitalkamera - 51 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick, Memory Stick PRO - sølv','SONY',1603.38,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot DSC-W7','Digitalkamera - 72 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick, Memory Stick PRO - sølv','SONY',2794.86,int(rand()* 100),now() - int(rand() * 100) days),
('Cyber-shot U DSC-U50S','Digitalkamera - 20 Mpix - understøttet hukommelse: Memory Stick Duo - sølv','SONY',2493.85,int(rand()* 100),now() - int(rand() * 100) days),
('Digimax A4','Digitalkamera - 40 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD','SAMSUNG',2381.16,int(rand()* 100),now() - int(rand() * 100) days),
('Digimax A5','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD','SAMSUNG',2501.62,int(rand()* 100),now() - int(rand() * 100) days),
('Digimax A6','Digitalkamera - 60 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD','SAMSUNG',2108.44,int(rand()* 100),now() - int(rand() * 100) days),
('Digimax L50','Digitalkamera - 50 Mpix - optisk zoom: 28 x - understøttet hukommelse: MMC, SD','SAMSUNG',2425.28,int(rand()* 100),now() - int(rand() * 100) days),
('Digimax U-CA 3','Digitalkamera - 32 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick PRO Duo','SAMSUNG',2074.41,int(rand()* 100),now() - int(rand() * 100) days),
('Digimax U-CA 4','Digitalkamera - 41 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick Duo, Memory Stick PRO Duo - titan','SAMSUNG',1532.51,int(rand()* 100),now() - int(rand() * 100) days),
('Digimax U-CA 505','Digitalkamera - 50 Mpix - understøttet hukommelse: MMC, SD','SAMSUNG',3195.89,int(rand()* 100),now() - int(rand() * 100) days),
('Digimax u-ca5','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD - bl√•','SAMSUNG',1780.86,int(rand()* 100),now() - int(rand() * 100) days),
('Digimax u-ca5','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD - rød','SAMSUNG',1815.96,int(rand()* 100),now() - int(rand() * 100) days),
('Digimax u-ca5','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD - sølv','SAMSUNG',2115.5,int(rand()* 100),now() - int(rand() * 100) days),
('Digimax V50','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick Duo, MMC, SD, Memory Stick PRO Duo','SAMSUNG',1979.22,int(rand()* 100),now() - int(rand() * 100) days),
('Digimax V70','Digitalkamera - 70 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD','SAMSUNG',1329.33,int(rand()* 100),now() - int(rand() * 100) days),
('Digimax V700','Digitalkamera - 71 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD - bl√•','SAMSUNG',1671.21,int(rand()* 100),now() - int(rand() * 100) days),
('Digimax V700','Digitalkamera - 71 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD - rød','SAMSUNG',3129.38,int(rand()* 100),now() - int(rand() * 100) days),
('Digimax V700','Digitalkamera - 71 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD - sølv','SAMSUNG',3129.38,int(rand()* 100),now() - int(rand() * 100) days),
('Digital IXUS i Zoom','Digitalkamera - 50 Mpix - optisk zoom: 24 x - understøttet hukommelse: MMC, SD - jet','CANON',2984.16,int(rand()* 100),now() - int(rand() * 100) days),
('Digital IXUS i Zoom','Digitalkamera - 50 Mpix - optisk zoom: 24 x - understøttet hukommelse: MMC, SD - sahara','CANON',1619.76,int(rand()* 100),now() - int(rand() * 100) days),
('Digital IXUS i Zoom','Digitalkamera - 50 Mpix - optisk zoom: 24 x - understøttet hukommelse: MMC, SD - tytteb√¶r','CANON',1619.76,int(rand()* 100),now() - int(rand() * 100) days),
('Digital IXUS i Zoom','Digitalkamera - 50 Mpix - optisk zoom: 24 x - understøttet hukommelse: MMC, SD - ultraviolet','CANON',1619.76,int(rand()* 100),now() - int(rand() * 100) days),
('Digital IXUS i 5','Digitalkamera - 50 Mpix - understøttet hukommelse: SD - bordeauxrød','CANON',1790.86,int(rand()* 100),now() - int(rand() * 100) days),
('Digital IXUS i 5','Digitalkamera - 50 Mpix - understøttet hukommelse: SD - bordeauxrød','CANON',1790.86,int(rand()* 100),now() - int(rand() * 100) days),
('Digital IXUS i 5','Digitalkamera - 50 Mpix - understøttet hukommelse: SD - midnatsbl√•','CANON',2048.17,int(rand()* 100),now() - int(rand() * 100) days),
('Digital IXUS i 5','Digitalkamera - 50 Mpix - understøttet hukommelse: SD - stormgr√•','CANON',2048.17,int(rand()* 100),now() - int(rand() * 100) days),
('Digital IXUS 40','Digitalkamera - 40 Mpix - optisk zoom: 3 x - understøttet hukommelse: SD','CANON',1636.2,int(rand()* 100),now() - int(rand() * 100) days),
('Digital IXUS 40','Digitalkamera - 40 Mpix - optisk zoom: 3 x - understøttet hukommelse: SD','CANON',1636.2,int(rand()* 100),now() - int(rand() * 100) days),
('Digital IXUS 50','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: SD','CANON',2817.15,int(rand()* 100),now() - int(rand() * 100) days),
('Digital IXUS 50','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: SD','CANON',2803.52,int(rand()* 100),now() - int(rand() * 100) days),
('Digital IXUS 55','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: SD','CANON',2691.89,int(rand()* 100),now() - int(rand() * 100) days),
('Digital IXUS 55','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: SD','CANON',2691.89,int(rand()* 100),now() - int(rand() * 100) days),
('Digital IXUS 700','Digitalkamera - 71 Mpix - optisk zoom: 3 x - understøttet hukommelse: SD','CANON',1329.76,int(rand()* 100),now() - int(rand() * 100) days),
('Digital IXUS 700','Digitalkamera - 71 Mpix - optisk zoom: 3 x - understøttet hukommelse: SD','CANON',1329.76,int(rand()* 100),now() - int(rand() * 100) days),
('Digital IXUS 750','Digitalkamera - 71 Mpix - optisk zoom: 3 x - understøttet hukommelse: SD - sølv','CANON',2024.28,int(rand()* 100),now() - int(rand() * 100) days),
('Digital IXUS 750','Digitalkamera - 71 Mpix - optisk zoom: 3 x - understøttet hukommelse: SD - sølv','CANON',2024.28,int(rand()* 100),now() - int(rand() * 100) days),
('D100','Digitalkamera - SLR - 61 Mpix - kun kamerahus - understøttet hukommelse: CF - sort','NIKON',3175.7,int(rand()* 100),now() - int(rand() * 100) days),
('D2HS','Digitalkamera - SLR - 41 Mpix - kun kamerahus - understøttet hukommelse: CF, Microdrive','NIKON',2616.72,int(rand()* 100),now() - int(rand() * 100) days),
('D50','Digitalkamera - SLR - 61 Mpix - kun kamerahus - understøttet hukommelse: SD - sort','NIKON',1915.03,int(rand()* 100),now() - int(rand() * 100) days),
('D50','Digitalkamera - SLR - 61 Mpix - kun kamerahus - understøttet hukommelse: SD - sølv','NIKON',3210.33,int(rand()* 100),now() - int(rand() * 100) days),
('D50','Digitalkamera - SLR - 61 Mpix - Nikon AF-S DX 18-55 mm objektiv - optisk zoom: 3 x - understøttet hukommelse: SD - sort','NIKON',2583.95,int(rand()* 100),now() - int(rand() * 100) days),
('D50','Digitalkamera - SLR - 61 Mpix - Nikon AF-S DX 18-55 mm objektiv - optisk zoom: 3 x - understøttet hukommelse: SD - sølv','NIKON',1992.85,int(rand()* 100),now() - int(rand() * 100) days),
('D70s','Digitalkamera - SLR - 61 Mpix - kun kamerahus - understøttet hukommelse: CF, Microdrive','NIKON',1350.65,int(rand()* 100),now() - int(rand() * 100) days),
('D70s','Digitalkamera - SLR - 61 Mpix - Nikon AF-S DX 18-70mm lens - optisk zoom: 38 x - understøttet hukommelse: CF, Microdrive','NIKON',3257.94,int(rand()* 100),now() - int(rand() * 100) days),
('E-1','Digitalkamera - SLR - 50 Mpix - Olympus Zuiko Digital 14-45 mm objektiv - optisk zoom: 32 x - understøttet hukommelse: CF, Microdrive','OLYMPUS',2542.56,int(rand()* 100),now() - int(rand() * 100) days),
('E-1','Digitalkamera - SLR - 50 Mpix - Olympus Zuiko digital 14-54 mm objektiv - optisk zoom: 39 x','OLYMPUS',3219.89,int(rand()* 100),now() - int(rand() * 100) days),
('E-300','Digitalkamera - SLR - 80 Mpix - kun kamerahus - understøttet hukommelse: CF, Microdrive','OLYMPUS',2326.53,int(rand()* 100),now() - int(rand() * 100) days),
('E-300','Digitalkamera - SLR - 80 Mpix - Olympus Zuiko Digital 14-4 5 mm og 40-150 objektiver - optisk zoom: 32 x - understøttet hukommelse: CF, Microdrive','OLYMPUS',2740.27,int(rand()* 100),now() - int(rand() * 100) days),
('E-300','Digitalkamera - SLR - 80 Mpix - Olympus Zuiko Digital 14-45 mm objektiv - optisk zoom: 32 x - understøttet hukommelse: CF, Microdrive','OLYMPUS',2970.76,int(rand()* 100),now() - int(rand() * 100) days),
('EasyShare C300','Digitalkamera - 32 Mpix - understøttet hukommelse: MMC, SD','KODAK',2492.28,int(rand()* 100),now() - int(rand() * 100) days),
('EasyShare C310','Digitalkamera - 40 Mpix - understøttet hukommelse: MMC, SD','KODAK',2638.79,int(rand()* 100),now() - int(rand() * 100) days),
('EasyShare C330','Digitalkamera - 40 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD','KODAK',2441.06,int(rand()* 100),now() - int(rand() * 100) days),
('EasyShare C340','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD','KODAK',1687.14,int(rand()* 100),now() - int(rand() * 100) days),
('EasyShare C360','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD','KODAK',1309.91,int(rand()* 100),now() - int(rand() * 100) days),
('EasyShare LS755','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: xD-Picture Card','KODAK',2116.76,int(rand()* 100),now() - int(rand() * 100) days),
('EasyShare V530','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD - midnat sort','KODAK',1491.15,int(rand()* 100),now() - int(rand() * 100) days),
('EasyShare V530','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD - sølvessens','KODAK',2922.64,int(rand()* 100),now() - int(rand() * 100) days),
('EasyShare V550','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD - sort','KODAK',1774.04,int(rand()* 100),now() - int(rand() * 100) days),
('EasyShare V550','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD - sølv','KODAK',3163.52,int(rand()* 100),now() - int(rand() * 100) days),
('EasyShare Z700','Digitalkamera - 40 Mpix - optisk zoom: 5 x - understøttet hukommelse: MMC, SD','KODAK',1652.74,int(rand()* 100),now() - int(rand() * 100) days),
('EasyShare Z700 with Prin','Digitalkamera - 40 Mpix - optisk zoom: 5 x - understøttet hukommelse: MMC, SD','KODAK',2237.56,int(rand()* 100),now() - int(rand() * 100) days),
('EasyShare Z730','Digitalkamera - 50 Mpix - optisk zoom: 4 x - understøttet hukommelse: MMC, SD','KODAK',1678.71,int(rand()* 100),now() - int(rand() * 100) days),
('EasyShare Z740','Digitalkamera - 50 Mpix - optisk zoom: 10 x - understøttet hukommelse: MMC, SD','KODAK',1627.4,int(rand()* 100),now() - int(rand() * 100) days),
('EasyShare Z7590','Digitalkamera - 50 Mpix - optisk zoom: 10 x - understøttet hukommelse: MMC, SD','KODAK',1663.32,int(rand()* 100),now() - int(rand() * 100) days),
('EOS 1D Mark II','Digitalkamera - SLR - 82 Mpix - kun kamerahus - understøttet hukommelse: CF, SD, Microdrive - sort','CANON',2457.16,int(rand()* 100),now() - int(rand() * 100) days),
('EOS 1D Mark II N','Digitalkamera - SLR - 82 Mpix - kun kamerahus - understøttet hukommelse: CF, SD, Microdrive','CANON',3223.24,int(rand()* 100),now() - int(rand() * 100) days),
('EOS 1Ds Mark II','Digitalkamera - SLR - 167 Mpix - kun kamerahus - understøttet hukommelse: CF, SD, Microdrive','CANON',1730.75,int(rand()* 100),now() - int(rand() * 100) days),
('EOS 1Ds Mark II','Digitalkamera - SLR - 167 Mpix - kun kamerahus - understøttet hukommelse: CF, SD, Microdrive','CANON',2000.93,int(rand()* 100),now() - int(rand() * 100) days),
('EOS 20D','Digitalkamera - SLR - 82 Mpix - Canon EF-S 17-85 mm IS linse - optisk zoom: 5 x - understøttet hukommelse: CF, Microdrive','CANON',2914.42,int(rand()* 100),now() - int(rand() * 100) days),
('EOS 20D','Digitalkamera - SLR - 82 Mpix - Canon EF-S-objektiv, 18-55 mm - optisk zoom: 3 x - understøttet hukommelse: CF, Microdrive','CANON',3167.22,int(rand()* 100),now() - int(rand() * 100) days),
('EOS 20D','Digitalkamera - SLR - 82 Mpix - Canon EF-S-objektiv, 18-55 mm - optisk zoom: 3 x - understøttet hukommelse: CF, Microdrive','CANON',2174.41,int(rand()* 100),now() - int(rand() * 100) days),
('EOS 20D','Digitalkamera - SLR - 82 Mpix - kun kamerahus - understøttet hukommelse: CF, Microdrive','CANON',2763.51,int(rand()* 100),now() - int(rand() * 100) days),
('EOS 20D','Digitalkamera - SLR - 82 Mpix - kun kamerahus - understøttet hukommelse: CF, Microdrive','CANON',2442.33,int(rand()* 100),now() - int(rand() * 100) days),
('EOS 350D','Digitalkamera - SLR - 80 Mpix - Canon EF-S 17-85 mm IS linse - optisk zoom: 5 x - understøttet hukommelse: CF, Microdrive - sort','CANON',2008.45,int(rand()* 100),now() - int(rand() * 100) days),
('EOS 350D','Digitalkamera - SLR - 80 Mpix - Canon EF-S 18-55 mm og EF 55-200 objektiver - optisk zoom: 3 x - understøttet hukommelse: CF, Microdrive','CANON',2862.52,int(rand()* 100),now() - int(rand() * 100) days),
('EOS 350D','Digitalkamera - SLR - 80 Mpix - Canon EF-S-objektiv, 18-55 mm - optisk zoom: 3 x - understøttet hukommelse: CF, Microdrive','CANON',3187.68,int(rand()* 100),now() - int(rand() * 100) days),
('EOS 350D','Digitalkamera - SLR - 80 Mpix - Canon EF-S-objektiv, 18-55 mm - optisk zoom: 3 x - understøttet hukommelse: CF, Microdrive','CANON',2116.64,int(rand()* 100),now() - int(rand() * 100) days),
('EOS 350D','Digitalkamera - SLR - 80 Mpix - kun kamerahus - understøttet hukommelse: CF, Microdrive','CANON',2242.18,int(rand()* 100),now() - int(rand() * 100) days),
('EOS 5D','Digitalkamera - SLR - 128 Mpix - kun kamerahus - understøttet hukommelse: CF, Microdrive','CANON',2907.24,int(rand()* 100),now() - int(rand() * 100) days),
('EXILIM EX-Z3','Digitalkamera - 32 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD','CASIO',1757.29,int(rand()* 100),now() - int(rand() * 100) days),
('EXILIM EX-Z30','Digitalkamera - 32 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD - sølv','CASIO',2761.43,int(rand()* 100),now() - int(rand() * 100) days),
('EXILIM Pro EX-P505','Digitalkamera - 50 Mpix - optisk zoom: 5 x - understøttet hukommelse: MMC, SD','CASIO',3113.47,int(rand()* 100),now() - int(rand() * 100) days),
('EXILIM Pro EX-P600','Digitalkamera - 60 Mpix - optisk zoom: 4 x - understøttet hukommelse: MMC, SD','CASIO',1958.44,int(rand()* 100),now() - int(rand() * 100) days),
('EXILIM ZOOM EX-Z57','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD','CASIO',2828.31,int(rand()* 100),now() - int(rand() * 100) days),
('EXILIM ZOOM EX-Z750','Digitalkamera - 72 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD - sølv','CASIO',2049.47,int(rand()* 100),now() - int(rand() * 100) days),
('Ferrari DIGITAL MODEL','Digitalkamera - 32 Mpix - optisk zoom: 3 x - understøttet hukommelse: xD-Picture Card - Ferrari rød','OLYMPUS',2712.17,int(rand()* 100),now() - int(rand() * 100) days),
('FinePix A345','Digitalkamera - 41 Mpix - optisk zoom: 3 x - understøttet hukommelse: xD-Picture Card','FUJIFILM',1935.23,int(rand()* 100),now() - int(rand() * 100) days),
('FinePix A350','Digitalkamera - 52 Mpix - optisk zoom: 3 x - understøttet hukommelse: xD-Picture Card','FUJIFILM',2647.47,int(rand()* 100),now() - int(rand() * 100) days),
('FinePix E550 Zoom','Digitalkamera - 63 Mpix - optisk zoom: 4 x - understøttet hukommelse: xD-Picture Card','FUJIFILM',3274.03,int(rand()* 100),now() - int(rand() * 100) days),
('FinePix F10','Digitalkamera - 63 Mpix - optisk zoom: 3 x - understøttet hukommelse: xD-Picture Card','FUJIFILM',2657.85,int(rand()* 100),now() - int(rand() * 100) days),
('FinePix F810 Zoom','Digitalkamera - 63 Mpix / 123 Mpix (interpoleret) - optisk zoom: 4 x - understøttet hukommelse: xD-Picture Card','FUJIFILM',2957.86,int(rand()* 100),now() - int(rand() * 100) days),
('FinePix S3 Pro','Digitalkamera - SLR - 123 Mpix - kun kamerahus - understøttet hukommelse: CF, xD-Picture Card, Microdrive','FUJIFILM',2601.7,int(rand()* 100),now() - int(rand() * 100) days),
('FinePix Z1','Digitalkamera - 51 Mpix - optisk zoom: 3 x - understøttet hukommelse: xD-Picture Card','FUJIFILM',3215.59,int(rand()* 100),now() - int(rand() * 100) days),
('IR-300','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: xD-Picture Card','OLYMPUS',1396.18,int(rand()* 100),now() - int(rand() * 100) days),
('Lumix DMC-FX2','Digitalkamera - 40 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD - sølv','PANASONIC',1440.31,int(rand()* 100),now() - int(rand() * 100) days),
('Lumix DMC-FX8EG-P','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD - rosa','PANASONIC',1791.43,int(rand()* 100),now() - int(rand() * 100) days),
('Lumix DMC-FX8EG-S','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD - sølv','PANASONIC',1611.04,int(rand()* 100),now() - int(rand() * 100) days),
('Lumix DMC-FX8EGM-A','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD - bl√•','PANASONIC',1885.93,int(rand()* 100),now() - int(rand() * 100) days),
('Lumix DMC-FX8EGM-K','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD - sort','PANASONIC',3146.2,int(rand()* 100),now() - int(rand() * 100) days),
('Lumix DMC-FX9EG-K','Digitalkamera - 60 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD - sort','PANASONIC',2958.89,int(rand()* 100),now() - int(rand() * 100) days),
('Lumix DMC-FX9EG-S','Digitalkamera - 60 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD - sølv','PANASONIC',1362.82,int(rand()* 100),now() - int(rand() * 100) days),
('Lumix DMC-FZ20EG-K','Digitalkamera - 50 Mpix - optisk zoom: 12 x - understøttet hukommelse: MMC, SD - sort','PANASONIC',2428.61,int(rand()* 100),now() - int(rand() * 100) days),
('Lumix DMC-FZ20EGMS','Digitalkamera - 50 Mpix - optisk zoom: 12 x - understøttet hukommelse: MMC, SD - sølv','PANASONIC',2497.6,int(rand()* 100),now() - int(rand() * 100) days),
('Lumix DMC-FZ5EGM-K','Digitalkamera - 50 Mpix - optisk zoom: 12 x - understøttet hukommelse: MMC, SD - sort','PANASONIC',2254.54,int(rand()* 100),now() - int(rand() * 100) days),
('Lumix DMC-FZ5EGM-S','Digitalkamera - 50 Mpix - optisk zoom: 12 x - understøttet hukommelse: MMC, SD - sølv','PANASONIC',3232.59,int(rand()* 100),now() - int(rand() * 100) days),
('Lumix DMC-LC1E-K','Digitalkamera - 50 Mpix - optisk zoom: 32 x - understøttet hukommelse: MMC, SD','PANASONIC',3241.91,int(rand()* 100),now() - int(rand() * 100) days),
('Lumix DMC-LC80EGM-S','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD - sølv','PANASONIC',2495.77,int(rand()* 100),now() - int(rand() * 100) days),
('Lumix DMC-LS1EGM-S','Digitalkamera - 40 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD - sølv','PANASONIC',2407.09,int(rand()* 100),now() - int(rand() * 100) days),
('Lumix DMC-LZ1EGM-S','Digitalkamera - 40 Mpix - optisk zoom: 6 x - understøttet hukommelse: MMC, SD - sølv','PANASONIC',2717.43,int(rand()* 100),now() - int(rand() * 100) days),
('Lumix DMC-LZ2EG-K','Digitalkamera - 50 Mpix - optisk zoom: 6 x - understøttet hukommelse: MMC, SD - sort','PANASONIC',1645.37,int(rand()* 100),now() - int(rand() * 100) days),
('Lumix DMC-LZ2EGM-S','Digitalkamera - 50 Mpix - optisk zoom: 6 x - understøttet hukommelse: MMC, SD - sølv','PANASONIC',3077.15,int(rand()* 100),now() - int(rand() * 100) days),
('Mavica MVC-FD200','Digitalkamera - 20 Mpix - optisk zoom: 3 x - understøttet hukommelse: Memory Stick - sort, metalsølv','SONY',1327.73,int(rand()* 100),now() - int(rand() * 100) days),
('Minolta DiMAGE A200','Digitalkamera - SLR-type - 80 Mpix - optisk zoom: 7 x - understøttet hukommelse: CF, Microdrive','KONICA',2308.69,int(rand()* 100),now() - int(rand() * 100) days),
('Minolta DiMAGE E500','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: SD','KONICA',1377.36,int(rand()* 100),now() - int(rand() * 100) days),
('Minolta DiMAGE X1','Digitalkamera - 80 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD - rød','KONICA',2931.94,int(rand()* 100),now() - int(rand() * 100) days),
('Minolta DiMAGE X1','Digitalkamera - 80 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD - sort','KONICA',2931.94,int(rand()* 100),now() - int(rand() * 100) days),
('Minolta DiMAGE X1','Digitalkamera - 80 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD - sølv','KONICA',1980.87,int(rand()* 100),now() - int(rand() * 100) days),
('Minolta DiMAGE X60','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD - bl√•','KONICA',3179.6,int(rand()* 100),now() - int(rand() * 100) days),
('Minolta DiMAGE X60','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD - sølv','KONICA',3179.6,int(rand()* 100),now() - int(rand() * 100) days),
('Minolta DiMAGE Z3','Digitalkamera - SLR-type - 40 Mpix - optisk zoom: 12 x - understøttet hukommelse: MMC, SD','KONICA',3180.62,int(rand()* 100),now() - int(rand() * 100) days),
('Minolta DiMAGE Z3','Digitalkamera - SLR-type - 40 Mpix - optisk zoom: 12 x - understøttet hukommelse: MMC, SD - sort','KONICA',2665.88,int(rand()* 100),now() - int(rand() * 100) days),
('Minolta DiMAGE Z5','Digitalkamera - SLR-type - 50 Mpix - optisk zoom: 12 x - understøttet hukommelse: MMC, SD - sort','KONICA',1680.01,int(rand()* 100),now() - int(rand() * 100) days),
('Minolta DiMAGE Z5','Digitalkamera - SLR-type - 50 Mpix - optisk zoom: 12 x - understøttet hukommelse: MMC, SD - sølv','KONICA',1911.38,int(rand()* 100),now() - int(rand() * 100) days),
('Minolta DiMAGE Z6','Digitalkamera - SLR-type - 60 Mpix - optisk zoom: 12 x - understøttet hukommelse: MMC, SD - sort','KONICA',3095.74,int(rand()* 100),now() - int(rand() * 100) days),
('Minolta DiMAGE Z6','Digitalkamera - SLR-type - 60 Mpix - optisk zoom: 12 x - understøttet hukommelse: MMC, SD - sølv','KONICA',1663.32,int(rand()* 100),now() - int(rand() * 100) days),
('Minolta Dynax 5D','Digitalkamera - SLR - 61 Mpix - Konica Minolta AF DT 18-70 mm objektiv - optisk zoom: 39 x - understøttet hukommelse: CF, Microdrive','KONICA',2319.28,int(rand()* 100),now() - int(rand() * 100) days),
('Minolta Dynax 7D','Digitalkamera - SLR - 61 Mpix - kun kamerahus - understøttet hukommelse: CF, Microdrive','KONICA',2098.82,int(rand()* 100),now() - int(rand() * 100) days),
('PhotoSmart E317','Digitalkamera - 50 Mpix - understøttet hukommelse: MMC, SD','HP',2303.82,int(rand()* 100),now() - int(rand() * 100) days),
('PhotoSmart M22','Digitalkamera - 41 Mpix - understøttet hukommelse: MMC, SD','HP',2715.7,int(rand()* 100),now() - int(rand() * 100) days),
('PhotoSmart R817','Digitalkamera - 51 Mpix - optisk zoom: 5 x - understøttet hukommelse: MMC, SD','HP',2366.03,int(rand()* 100),now() - int(rand() * 100) days),
('PhotoSmart R817','Digitalkamera - 51 Mpix - optisk zoom: 5 x - understøttet hukommelse: MMC, SD','HP',2348.47,int(rand()* 100),now() - int(rand() * 100) days),
('PowerShot A400','Digitalkamera - 32 Mpix - optisk zoom: 22 x - understøttet hukommelse: SD - for√•rsgrøn','CANON',1532.11,int(rand()* 100),now() - int(rand() * 100) days),
('PowerShot A400','Digitalkamera - 32 Mpix - optisk zoom: 22 x - understøttet hukommelse: SD - gul solnedgang','CANON',1532.11,int(rand()* 100),now() - int(rand() * 100) days),
('PowerShot A410','Digitalkamera - 32 Mpix - optisk zoom: 32 x - understøttet hukommelse: MMC, SD','CANON',1943.63,int(rand()* 100),now() - int(rand() * 100) days),
('PowerShot A520','Digitalkamera - 40 Mpix - optisk zoom: 4 x - understøttet hukommelse: MMC, SD','CANON',1935.23,int(rand()* 100),now() - int(rand() * 100) days),
('PowerShot A610','Digitalkamera - 50 Mpix - optisk zoom: 4 x - understøttet hukommelse: MMC, SD','CANON',3274.85,int(rand()* 100),now() - int(rand() * 100) days),
('PowerShot A620','Digitalkamera - 71 Mpix - optisk zoom: 4 x - understøttet hukommelse: MMC, SD','CANON',3018.17,int(rand()* 100),now() - int(rand() * 100) days),
('PowerShot G6','Digitalkamera - 71 Mpix - optisk zoom: 4 x - understøttet hukommelse: CF, Microdrive','CANON',3140.14,int(rand()* 100),now() - int(rand() * 100) days),
('PowerShot Pro1','Digitalkamera - 80 Mpix - optisk zoom: 7 x - understøttet hukommelse: CF, Microdrive','CANON',1664.66,int(rand()* 100),now() - int(rand() * 100) days),
('PowerShot S1 IS','Digitalkamera - 32 Mpix - optisk zoom: 10 x - understøttet hukommelse: CF, Microdrive','CANON',3181.14,int(rand()* 100),now() - int(rand() * 100) days),
('PowerShot S2 IS','Digitalkamera - 50 Mpix - optisk zoom: 12 x - understøttet hukommelse: SD','CANON',1853.26,int(rand()* 100),now() - int(rand() * 100) days),
('PowerShot S60','Digitalkamera - 50 Mpix - optisk zoom: 36 x - understøttet hukommelse: CF, Microdrive','CANON',1628.86,int(rand()* 100),now() - int(rand() * 100) days),
('PowerShot S70','Digitalkamera - 71 Mpix - optisk zoom: 36 x - understøttet hukommelse: CF, Microdrive - sort','CANON',1371.64,int(rand()* 100),now() - int(rand() * 100) days),
('PowerShot S80','Digitalkamera - 80 Mpix - optisk zoom: 36 x - understøttet hukommelse: MMC, SD','CANON',2684.96,int(rand()* 100),now() - int(rand() * 100) days),
('QV-R41','Digitalkamera - 40 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD','CASIO',2743.95,int(rand()* 100),now() - int(rand() * 100) days),
('QV-R51','Digitalkamera - 50 Mpix - optisk zoom: 3 x - understøttet hukommelse: MMC, SD','CASIO',2615.52,int(rand()* 100),now() - int(rand() * 100) days),
('SP-500 UltraZoom','Digitalkamera - 60 Mpix - optisk zoom: 10 x - understøttet hukommelse: xD-Picture Card','OLYMPUS',2846.15,int(rand()* 100),now() - int(rand() * 100) days),
('µDIGITAL 600 ex','Super flex OL TWO2','OLYMPUS',2498.7,int(rand()* 100),now() - int(rand() * 100) days);
commit;

select * from microdemo.ilproducts;
