CMD  PROMPT('OpenAPI Source Generator')

    PARM KWD(INPATH) TYPE(*PNAME) LEN(1000) KEYPARM(*NO) PROMPT('Input Stream File Path') CASE(*MIXED) MIN(1) MAX(100)
PARM KWD(DOCPATH) TYPE(*CHAR) LEN(1000) KEYPARM(*NO) PROMPT('OpenAPI Document Path') CASE(*MIXED)